### ISSUE TITLE
Update Docs. Very less information or wrong information

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/Mail-for-Good#124]
1. First of all, I see that the App is exposed at port 8080 in my computer. Is it because it recognizes the environment as a dev environment ? But I didn't set any environment of that sort, so I think the App is exposed at port 8080 by default and not 80 as mentioned in the Docs

2. Developers should be informed to apply for SES limit increase in the Docs. I learned this from a YouTube tutorial when checking about SES.

3. Developers should also be informed about how to setup and get their Goolgle OAuth credentials by creating a project in the Google Developers Console and how they should set authorized origins and redirect (or callback) URLs

4. Developers should be informed to create a User in Amazon IAM and that the user should be given both programmatic and console access like below : 

![mail for good](https://user-images.githubusercontent.com/12808424/26964980-84015e70-4d11-11e7-8c3a-a3df2fb62d24.png)

so that it creates an auto-generated password too for the user, which has to be set in the `.env` file. Or else it creates a lot of issues! And password isn't optional, from what I see in the application

5. The links to install docker is all good. But I see that there are some issues with running the command `docker-compose up` and works only if we use `sudo docker-compose up` or else we have to create something called Docker group it seems, to get rid of the `sudo` . Check this : 
[Stack Overflow Issue](https://stackoverflow.com/questions/34532696/docker-compose-cant-connect-to-docker-daemon)

**Comment by karuppiah7890** [comment]
@AndrewGHC I can make PRs actually. But do tell about refinements and I will work on this. 

I also plan to create a simple tutorial for the whole setup in Medium

**Comment by AndrewGHC** [comment]
@karuppiah7890 Thanks again for this feedback, you've identified some key issues with the Readme that I've now fixed.

1. Thanks for spotting this, I've now corrected the port.
2. This information is now included.
3. This information is now included.
4. This process is currently described in the tutorial video - but it is a good point that we may need to write this process down.
5. Root permissions shouldn't be necessary to run Docker, the issue in the SO link has multiple competing solutions, suggesting that this may be an issue with specific version of Docker.

Thanks again for your feedback.

**Comment by karuppiah7890** [comment]
@AndrewGHC For 4, the procedure isn't explained properly in the video. @QuincyLarson only asks us to create a pair of Access Key and Secret Access Key, see here [YouTube Demo 1m:22s](https://youtu.be/_7U03GVD4a8?t=1m22s). He doesn't tick the AWS Management Console Access. The demo still works. I guess it wasn't a problem then. But now, the `.env` file instructions mention that AWS Access keys are encrypted with the user specific password. So, if no password is created for the user, I don't know if Amazon encrypts or what happens, but the application however throws an error about no passwords in `.env`, in the console

**Comment by karuppiah7890** [comment]
@AndrewGHC  And about 5, well, I have the latest version of Docker. And I am still getting issues. Are you sure there is no procedure of even adding the user to the docker group ? Because I was just trying that, and it doesn't seem to work out. Searching what is the issue
