### ISSUE TITLE
PostgreSQL Error When Running docker-compose up

### ISSUE THREAD

**Issue by ZaynMalloc** [freeCodeCamp/Mail-for-Good#153]
I cloned the repo, but I cannot get the application to run properly. I can connect to the login page, but authentication fails when you click the sign in button. I ran `sudo docker-compose up`. However, I get this error. 

```
zach@zach-VirtualBox:~/Documents/Code/Mail-for-Good$ sudo docker-compose up
Creating mailforgood_postgres_1
Creating mailforgood_redis_1
Creating mailforgood_app_1
Attaching to mailforgood_redis_1, mailforgood_postgres_1, mailforgood_app_1
redis_1     | 1:C 01 Jul 06:51:00.151 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1     | 1:M 01 Jul 06:51:00.157 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1     | 1:M 01 Jul 06:51:00.157 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
redis_1     | 1:M 01 Jul 06:51:00.157 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients incre
ase 'ulimit -n'.
redis_1     |                 _._
redis_1     |            _.-``__ ''-._
redis_1     |       _.-``    `.  `_.  ''-._           Redis 3.2.9 (00000000/0) 64 bit
redis_1     |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1     |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1     |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1     |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1     |   `-._    `-._  `-./  _.-'    _.-'
redis_1     |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1     |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1     |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1     |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1     |  |    `-._`-._        _.-'_.-'    |
redis_1     |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1     |       `-._    `-.__.-'    _.-'
redis_1     |           `-._        _.-'
redis_1     |               `-.__.-'
redis_1     |
redis_1     | 1:M 01 Jul 06:51:00.158 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 01 Jul 06:51:00.158 # Server started, Redis version 3.2.9
redis_1     | 1:M 01 Jul 06:51:00.158 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory =
 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 01 Jul 06:51:00.158 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis
. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a r
eboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 01 Jul 06:51:00.158 * The server is now ready to accept connections on port 6379
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@4.2.0
app_1       | npm info using node@v7.10.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~prestart: nonprofit-email-service@1.0.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start: nonprofit-email-service@1.0.0
app_1       |
app_1       | > nonprofit-email-service@1.0.0 start /usr/src/app
app_1       | > NODE_ENV=production ./node_modules/pm2/bin/pm2 start server/index.js --node-args="--harmony-async-await" server/feedback-consumer/consumer.js --no-daemon
app_1       |
postgres_1  | running bootstrap script ... ok
app_1       |
app_1       |                         -------------
app_1       |
app_1       | __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
app_1       |  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
app_1       |   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
app_1       |    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
app_1       |     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
app_1       |      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
app_1       |       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
app_1       |        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
app_1       |         _\///______________\///______________\///__\///////////////__
app_1       |
app_1       |
app_1       |          Welcome to most Advanced Process Manager for Node.js
app_1       |
app_1       |                           Monitoring
app_1       |                         $ pm2 monitor
app_1       |
app_1       |                       Start PM2 at boot
app_1       |                         $ pm2 startup
app_1       |
app_1       |                      Increase Performance
app_1       |                     $ pm2 start api.js -i 4
app_1       |
app_1       |                         -------------
app_1       |
app_1       | pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
app_1       | 2017-07-01 06:51:03: Launching in no daemon mode
app_1       | 2017-07-01 06:51:03: [PM2] Starting /usr/src/app/server/index.js in fork_mode (1 instance)
app_1       | 2017-07-01 06:51:03: Starting execution sequence in -fork mode- for app name:index id:0
app_1       | 2017-07-01 06:51:03: App name:index id:0 online
app_1       | 2017-07-01 06:51:04: [PM2] Done.
postgres_1  | performing post-bootstrap initialization ... ok
app_1       | 2017-07-01 06:51:04: [PM2] Starting /usr/src/app/server/feedback-consumer/consumer.js in fork_mode (1 instance)
app_1       | 2017-07-01 06:51:04: Starting execution sequence in -fork mode- for app name:consumer id:1
app_1       | 2017-07-01 06:51:04: App name:consumer id:1 online
app_1       | 2017-07-01 06:51:04: [PM2] Done.
app_1       | 2017-07-01 06:51:04: ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
app_1       | │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem       │ watching │
app_1       | ├──────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
app_1       | │ consumer │ 1  │ fork │ 42  │ online │ 0       │ 0s     │ 18% │ 27.3 MB   │ disabled │
app_1       | │ index    │ 0  │ fork │ 25  │ online │ 0       │ 0s     │ 3%  │ 26.7 MB   │ disabled │
app_1       | └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
app_1       | 2017-07-01 06:51:04:  Use `pm2 show <id|name>` to get more details about an app
app_1       | 2017-07-01 06:51:04: [--no-daemon] Continue to stream logs
app_1       | 2017-07-01 06:51:04: [--no-daemon] Exit on target PM2 exit pid=15
app_1       | 2017-07-01 06:51:04: [STREAMING] Now streaming realtime logs for [all] processes
postgres_1  | syncing data to disk ... ok
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  |
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | ****************************************************
postgres_1  | WARNING: No password has been set for the database.
postgres_1  |          This will allow anyone with access to the
postgres_1  |          Postgres port to access your database. In
postgres_1  |          Docker's default configuration, this is
postgres_1  |          effectively any other container on the same
postgres_1  |          system.
postgres_1  |
postgres_1  |          Use "-e POSTGRES_PASSWORD=password" to set
postgres_1  |          it in "docker run".
postgres_1  | ****************************************************
postgres_1  | waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
postgres_1  | HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
postgres_1  | LOG:  database system was shut down at 2017-07-01 06:51:04 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
app_1       | 06:51:06 1|consumer | Feedback consumer started: watching for feedback messages (bounces, complaints, etc) from SQS
app_1       | 06:51:06 1|consumer | An error occurred while creating the table: { SequelizeBaseError: connect ECONNREFUSED 172.17.0.3:5432
app_1       | 06:51:06 1|consumer |     at connection.connect.err (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:92:24)
app_1       | 06:51:06 1|consumer |     at Client.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:201:5)
app_1       | 06:51:06 1|consumer |     at emitOne (events.js:96:13)
app_1       | 06:51:06 1|consumer |     at Connection.emit (events.js:191:7)
app_1       | 06:51:06 1|consumer |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:86:10)
app_1       | 06:51:06 1|consumer |     at emitOne (events.js:96:13)
app_1       | 06:51:06 1|consumer |     at Socket.emit (events.js:191:7)
app_1       | 06:51:06 1|consumer |     at emitErrorNT (net.js:1279:8)
app_1       | 06:51:06 1|consumer |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
app_1       | 06:51:06 1|consumer |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
app_1       | 06:51:06 1|consumer |   name: 'SequelizeConnectionRefusedError',
app_1       | 06:51:06 1|consumer |   parent:
app_1       | 06:51:06 1|consumer |    { Error: connect ECONNREFUSED 172.17.0.3:5432
app_1       | 06:51:06 1|consumer |        at Object.exports._errnoException (util.js:1050:11)
app_1       | 06:51:06 1|consumer |        at exports._exceptionWithHostPort (util.js:1073:20)
app_1       | 06:51:06 1|consumer |        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
app_1       | 06:51:06 1|consumer |      code: 'ECONNREFUSED',
app_1       | 06:51:06 1|consumer |      errno: 'ECONNREFUSED',
app_1       | 06:51:06 1|consumer |      syscall: 'connect',
app_1       | 06:51:06 1|consumer |      address: '172.17.0.3',
app_1       | 06:51:06 1|consumer |      port: 5432 },
app_1       | 06:51:06 1|consumer |   original:
app_1       | 06:51:06 1|consumer |    { Error: connect ECONNREFUSED 172.17.0.3:5432
app_1       | 06:51:06 1|consumer |        at Object.exports._errnoException (util.js:1050:11)
app_1       | 06:51:06 1|consumer |        at exports._exceptionWithHostPort (util.js:1073:20)
app_1       | 06:51:06 1|consumer |        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
app_1       | 06:51:06 1|consumer |      code: 'ECONNREFUSED',
app_1       | 06:51:06 1|consumer |      errno: 'ECONNREFUSED',
app_1       | 06:51:06 1|consumer |      syscall: 'connect',
app_1       | 06:51:06 1|consumer |      address: '172.17.0.3',
app_1       | 06:51:06 1|consumer |      port: 5432 } }
postgres_1  |  done
postgres_1  | server started
app_1       | 06:51:06 1|consumer | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
app_1       | 06:51:06 1|consumer | SequelizeBaseError: connect ECONNREFUSED 172.17.0.3:5432
app_1       | 06:51:06 1|consumer |     at connection.connect.err (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:92:24)
app_1       | 06:51:06 1|consumer |     at Client.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:201:5)
app_1       | 06:51:06 1|consumer |     at emitOne (events.js:96:13)
app_1       | 06:51:06 1|consumer |     at Connection.emit (events.js:191:7)
app_1       | 06:51:06 1|consumer |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:86:10)
app_1       | 06:51:06 1|consumer |     at emitOne (events.js:96:13)
app_1       | 06:51:06 1|consumer |     at Socket.emit (events.js:191:7)
app_1       | 06:51:06 1|consumer |     at emitErrorNT (net.js:1279:8)
app_1       | 06:51:06 1|consumer |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
app_1       | 06:51:06 1|consumer |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
postgres_1  | ALTER ROLE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | LOG:  received fast shutdown request
postgres_1  | LOG:  aborting any active transactions
postgres_1  | LOG:  autovacuum launcher shutting down
postgres_1  | LOG:  shutting down
postgres_1  | waiting for server to shut down....LOG:  database system is shut down
app_1       | 06:51:07 0|index    | Clickthrough tracking: Make sure that geoip data has been downloaded:
app_1       | 06:51:07 0|index    |    $ cd node_modules/geoip-lite
app_1       | 06:51:07 0|index    |    $ npm run-script updatedb
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | LOG:  database system was shut down at 2017-07-01 06:51:06 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
app_1       | 06:51:08 0|index    |   ############################
app_1       | 06:51:08 0|index    |
postgres_1  | ERROR:  relation "users" does not exist at character 112
postgres_1  | STATEMENT:  SELECT "id", "googleId", "picture", "token", "email", "name", "sentEmailsCount", "createdAt", "updatedAt" FROM "users" AS "user";
app_1       | 06:51:08 0|index    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
app_1       | 06:51:08 0|index    | SequelizeBaseError: relation "users" does not exist
app_1       | 06:51:08 0|index    |     at Query.formatError (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
app_1       | 06:51:08 0|index    |     at Query.query.on.err (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
app_1       | 06:51:08 0|index    |     at emitOne (events.js:96:13)
app_1       | 06:51:08 0|index    |     at Query.emit (events.js:191:7)
app_1       | 06:51:08 0|index    |     at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:143:8)
app_1       | 06:51:08 0|index    |     at Client.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:186:26)
app_1       | 06:51:08 0|index    |     at emitOne (events.js:96:13)
app_1       | 06:51:08 0|index    |     at Connection.emit (events.js:191:7)
app_1       | 06:51:08 0|index    |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:133:12)
app_1       | 06:51:08 0|index    |     at emitOne (events.js:96:13)
app_1       | 06:51:08 0|index    |     at Socket.emit (events.js:191:7)
app_1       | 06:51:08 0|index    |     at readableAddChunk (_stream_readable.js:178:18)
app_1       | 06:51:08 0|index    |     at Socket.Readable.push (_stream_readable.js:136:10)
app_1       | 06:51:08 0|index    |     at TCP.onread (net.js:561:20)
postgres_1  | ERROR:  column "listsubscriberId" does not exist
postgres_1  | STATEMENT:  CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")
postgres_1  | ERROR:  column "campaignId" does not exist
postgres_1  | STATEMENT:  CREATE INDEX "campaignsubscribers_campaign_id" ON "campaignsubscribers" ("campaignId")
app_1       | 06:51:09 0|index    | An error occurred while creating the table: { SequelizeBaseError: column "listsubscriberId" does not exist
app_1       | 06:51:09 0|index    |     at Query.formatError (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
app_1       | 06:51:09 0|index    |     at Query.query.on.err (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
app_1       | 06:51:09 0|index    |     at emitOne (events.js:96:13)
app_1       | 06:51:09 0|index    |     at Query.emit (events.js:191:7)
app_1       | 06:51:09 0|index    |     at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:143:8)
app_1       | 06:51:09 0|index    |     at Client.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:186:26)
app_1       | 06:51:09 0|index    |     at emitOne (events.js:96:13)
app_1       | 06:51:09 0|index    |     at Connection.emit (events.js:191:7)
app_1       | 06:51:09 0|index    |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:133:12)
app_1       | 06:51:09 0|index    |     at emitOne (events.js:96:13)
app_1       | 06:51:09 0|index    |     at Socket.emit (events.js:191:7)
app_1       | 06:51:09 0|index    |     at readableAddChunk (_stream_readable.js:178:18)
app_1       | 06:51:09 0|index    |     at Socket.Readable.push (_stream_readable.js:136:10)
app_1       | 06:51:09 0|index    |     at TCP.onread (net.js:561:20)
app_1       | 06:51:09 0|index    |   name: 'SequelizeDatabaseError',
app_1       | 06:51:09 0|index    |   parent:
app_1       | 06:51:09 0|index    |    { error: column "listsubscriberId" does not exist
app_1       | 06:51:09 0|index    |        at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:567:11)
app_1       | 06:51:09 0|index    |        at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:391:17)
app_1       | 06:51:09 0|index    |        at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:129:22)
app_1       | 06:51:09 0|index    |        at emitOne (events.js:96:13)
app_1       | 06:51:09 0|index    |        at Socket.emit (events.js:191:7)
app_1       | 06:51:09 0|index    |        at readableAddChunk (_stream_readable.js:178:18)
app_1       | 06:51:09 0|index    |        at Socket.Readable.push (_stream_readable.js:136:10)
app_1       | 06:51:09 0|index    |        at TCP.onread (net.js:561:20)
app_1       | 06:51:09 0|index    |      name: 'error',
app_1       | 06:51:09 0|index    |      length: 106,
app_1       | 06:51:09 0|index    |      severity: 'ERROR',
app_1       | 06:51:09 0|index    |      code: '42703',
app_1       | 06:51:09 0|index    |      detail: undefined,
app_1       | 06:51:09 0|index    |      hint: undefined,
app_1       | 06:51:09 0|index    |      position: undefined,
app_1       | 06:51:09 0|index    |      internalPosition: undefined,
app_1       | 06:51:09 0|index    |      internalQuery: undefined,
app_1       | 06:51:09 0|index    |      where: undefined,
app_1       | 06:51:09 0|index    |      schema: undefined,
app_1       | 06:51:09 0|index    |      table: undefined,
app_1       | 06:51:09 0|index    |      column: undefined,
app_1       | 06:51:09 0|index    |      dataType: undefined,
app_1       | 06:51:09 0|index    |      constraint: undefined,
app_1       | 06:51:09 0|index    |      file: 'indexcmds.c',
app_1       | 06:51:09 0|index    |      line: '1055',
app_1       | 06:51:09 0|index    |      routine: 'ComputeIndexAttrs',
app_1       | 06:51:09 0|index    |      sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' },
app_1       | 06:51:09 0|index    |   original:
app_1       | 06:51:09 0|index    |    { error: column "listsubscriberId" does not exist
app_1       | 06:51:09 0|index    |        at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:567:11)
app_1       | 06:51:09 0|index    |        at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:391:17)
app_1       | 06:51:09 0|index    |        at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:129:22)
app_1       | 06:51:09 0|index    |        at emitOne (events.js:96:13)
app_1       | 06:51:09 0|index    |        at Socket.emit (events.js:191:7)
app_1       | 06:51:09 0|index    |        at readableAddChunk (_stream_readable.js:178:18)
app_1       | 06:51:09 0|index    |        at Socket.Readable.push (_stream_readable.js:136:10)
app_1       | 06:51:09 0|index    |        at TCP.onread (net.js:561:20)
app_1       | 06:51:09 0|index    |      name: 'error',
app_1       | 06:51:09 0|index    |      length: 106,
app_1       | 06:51:09 0|index    |      severity: 'ERROR',
app_1       | 06:51:09 0|index    |      code: '42703',
app_1       | 06:51:09 0|index    |      detail: undefined,
app_1       | 06:51:09 0|index    |      hint: undefined,
app_1       | 06:51:09 0|index    |      position: undefined,
app_1       | 06:51:09 0|index    |      internalPosition: undefined,
app_1       | 06:51:09 0|index    |      internalQuery: undefined,
app_1       | 06:51:09 0|index    |      where: undefined,
app_1       | 06:51:09 0|index    |      schema: undefined,
app_1       | 06:51:09 0|index    |      table: undefined,
app_1       | 06:51:09 0|index    |      column: undefined,
app_1       | 06:51:09 0|index    |      dataType: undefined,
app_1       | 06:51:09 0|index    |      constraint: undefined,
app_1       | 06:51:09 0|index    |      file: 'indexcmds.c',
app_1       | 06:51:09 0|index    |      line: '1055',
app_1       | 06:51:09 0|index    |      routine: 'ComputeIndexAttrs',
app_1       | 06:51:09 0|index    |      sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' },
app_1       | 06:51:09 0|index    |   sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' }
app_1       | 07:04:17 0|index    | Error
app_1       | 07:04:17 0|index    |     at Strategy.OAuth2Strategy.parseErrorResponse (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:329:12)
app_1       | 07:04:17 0|index    |     at Strategy.OAuth2Strategy._createOAuthError (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:376:16)
app_1       | 07:04:17 0|index    |     at /usr/src/app/node_modules/passport-oauth2/lib/strategy.js:166:45
app_1       | 07:04:17 0|index    |     at /usr/src/app/node_modules/oauth/lib/oauth2.js:191:18
app_1       | 07:04:17 0|index    |     at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth2.js:132:9)
app_1       | 07:04:17 0|index    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:157:7)
app_1       | 07:04:17 0|index    |     at emitNone (events.js:91:20)
app_1       | 07:04:17 0|index    |     at IncomingMessage.emit (events.js:188:7)
app_1       | 07:04:17 0|index    |     at endReadableNT (_stream_readable.js:975:12)
app_1       | 07:04:17 0|index    |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
app_1       | 07:04:17 0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

```

**Comment by zhakkarn** [comment]
Did you authorize "http://localhost:8080/auth/google/callbackDid" to be a fallback uri in your google dashboard ?
also, did you put your Google+ API keys in your .env file ?

**Comment by zhakkarn** [comment]
I'm facing the same problems.
Alright, you can ignore my questions. 
I should have tested before commenting on this issue.
I'll take my afternoon to look at this. If you happen to be available today or tomorrow I'll be ablet to spend an hour or two to get you up and running.

**Comment by ZaynMalloc** [comment]
Thank you!

**Comment by karuppiah7890** [comment]
@zhakkarn Do you know which commit @AndrewGHC published to Docker Hub ?

**Comment by zhakkarn** [comment]
@karuppiah7890 as far as I know, @4iar handled the docker part of the project.

**Comment by 4iar** [comment]
@karuppiah7890 the Docker images are automatically built using the latest commits. 

Might this be related to PR #152? This fix has not yet been merged into master so the latest Docker image uses the newer broken Sequelize version (4.x.x). 

Maybe you could try running the staging Docker image (which uses the older Sequelize) by editing [docker-compose.yml](https://github.com/freeCodeCamp/Mail-for-Good/blob/master/docker-compose.yml) and setting:

Line 6:     image: freecodecamp/mail-for-good:latest
to 
Line 6:     image: freecodecamp/mail-for-good:staging

then re-run `docker-compose up`

**Comment by karuppiah7890** [comment]
Yes, I think we should keep the master branch stable first of all. That's why we have a master and a staging. So, let's merge #152 to master first. And then get the latest docker image built from master branch and upload it to Docker Hub

**Comment by AndrewGHC** [comment]
I have fixed this locally. Shall push changes shortly.

**Comment by karuppiah7890** [comment]
I am still getting these errors. The `docker-compose up` command doesn't start the app and throws some settings doesn't exist error. I don't get the `DB connected` message also. The same happens with the staging image too. Are the changes pushed ? I do see that the last push was 4 days ago,
cc @AndrewGHC @4iar
